### ISSUE TITLE
AUR包安装出错

### ISSUE THREAD

**Issue by KafCoppelia** [shih-liang/YesPlayMusicOSD#384]
通过AUR安装[`yesplaymusicosd-electron-git`](https://aur.archlinux.org/packages/yesplaymusicosd-electron-git)，其中`electron13`用`electron13-bin`替代。安装中遇到报错：

```
==> 正在开始 build()...

> yesplaymusic@0.4.5 electron:build-linux
> vue-cli-service electron:build -p never -l

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Bundling render process:

⠙  Building modern bundle for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
⠋  Building modern bundle for production...Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
⠙  Building modern bundle for production.../home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/cache-loader/dist/index.js:147:7
    at /home/kafcoppelia/.cache/yay/yesplaymusicosd-git/src/YesPlayMusicOSD-AUR/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:192:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
==> 错误： 在 build() 中发生一个错误。    正在放弃...
 -> 生成时出错: yesplaymusicosd-git (yesplaymusicosd-electron-git)
```

**Comment by Indusy** [comment]
试试 yesplaymusicosd-origin-electron 这个包

**Comment by Indusy** [comment]
刚才试了一下，应该是 node 版本问题，用 node 16 可以打包成功

**Comment by KafCoppelia** [comment]
AUR上`yesplaymusicosd-origin-electron`包确实可以安装成功，但是osd相关的两个打包（包括`electron`后缀）均比上游晚了两个版本……
